use once_cell::sync::Lazy;

use crate::models::ToolManifest;

pub static BUILTIN_TOOLS: Lazy<Vec<ToolManifest>> = Lazy::new(|| {
    vec![
        // ── Core wishlist repos ──────────────────────────────────────────────
        tool(
            "get-shit-done",
            "get-shit-done",
            "https://github.com/gsd-build/get-shit-done",
            "Runs the Ralph execution loop as a managed Bun workspace.",
            "bun run dev",
            "bun",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["agents", "automation"],
            false,
            true,
            true,
        ),
        tool(
            "vibe-kanban",
            "Vibe Kanban",
            "https://github.com/BloopAI/vibe-kanban",
            "Tracks work items and Ralph progress in a board-style workspace.",
            "bun run dev",
            "bun",
            vec!["OPENAI_API_KEY"],
            vec!["kanban", "productivity"],
            false,
            true,
            false,
        ),
        tool(
            "claudia",
            "Claudia",
            "https://github.com/getclaudia/claudia",
            "Consolidates memory and agent notes into a durable workspace.",
            "bun run dev",
            "bun",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["memory", "agents"],
            false,
            true,
            true,
        ),
        tool(
            "claude-code-templates",
            "Claude Code Templates",
            "https://github.com/davila7/claude-code-templates",
            "Bootstraps prompt and workflow templates for managed coding runs.",
            "bun run dev",
            "bun",
            vec!["ANTHROPIC_API_KEY"],
            vec!["templates", "coding"],
            false,
            true,
            false,
        ),
        tool(
            "perplexica",
            "Perplexica",
            "https://github.com/ItzCrazyKns/Perplexica",
            "AI-powered search engine with multi-source research for overnight workflows.",
            "bun run dev",
            "bun",
            vec!["PERPLEXICA_KEYS", "OPENAI_API_KEY"],
            vec!["research", "search"],
            true,
            true,
            true,
        ),
        tool(
            "llm-council",
            "LLM Council",
            "https://github.com/mkopecki/llm-council",
            "Model voting layer for combined workflows and overnight loops.",
            "pip install -e . && python -m llm_council",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY"],
            vec!["models", "orchestration"],
            false,
            true,
            true,
        ),
        tool(
            "autoresearch",
            "AutoResearch",
            "https://github.com/karpathy/minbpe",
            "Iterative research runner wired into RalphHub orchestration.",
            "pip install -e . && python main.py",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["research", "automation"],
            false,
            true,
            true,
        ),
        // ── Extended wishlist repos ──────────────────────────────────────────
        tool(
            "airi",
            "AIRI",
            "https://github.com/moeru-ai/airi",
            "Anime-style AI companion with voice, memory, and multi-model support.",
            "bun run dev",
            "bun",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["voice", "companion", "anime"],
            false,
            true,
            true,
        ),
        tool(
            "robin",
            "Robin",
            "https://github.com/Ikaika/robin",
            "Multi-agent research and task assistant with memory integration.",
            "pip install -e . && python -m robin",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["agents", "research"],
            false,
            true,
            true,
        ),
        tool(
            "scrapling",
            "Scrapling",
            "https://github.com/D4Vinci/Scrapling",
            "Undetectable fast web scraping with adaptive element tracking.",
            "pip install scrapling && python -m scrapling",
            "pip",
            vec![],
            vec!["scraping", "browser"],
            false,
            false,
            false,
        ),
        tool(
            "edgequake",
            "EdgeQuake",
            "https://github.com/NightCatSama/edgequake",
            "Edge-side AI inference runner for local model deployment.",
            "bun run dev",
            "bun",
            vec![],
            vec!["local-models", "inference"],
            false,
            true,
            false,
        ),
        tool(
            "blurr",
            "Blurr",
            "https://github.com/blurr-org/blurr",
            "Real-time AI video and image processing pipeline.",
            "pip install blurr && python -m blurr",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["vision", "media"],
            false,
            true,
            false,
        ),
        tool(
            "comfyui",
            "ComfyUI",
            "https://github.com/comfyanonymous/ComfyUI",
            "Node-based Stable Diffusion UI with full workflow automation.",
            "pip install -r requirements.txt && python main.py",
            "pip",
            vec![],
            vec!["image-gen", "stable-diffusion"],
            true,
            false,
            false,
        ),
        tool(
            "autogpt",
            "AutoGPT",
            "https://github.com/Significant-Gravitas/AutoGPT",
            "Autonomous AI agent that chains tasks and manages long-horizon goals.",
            "pip install -e . && python -m autogpt",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["agents", "automation"],
            false,
            true,
            true,
        ),
        tool(
            "metagpt",
            "MetaGPT",
            "https://github.com/geekan/MetaGPT",
            "Multi-role software company simulation driven by a single requirement.",
            "pip install metagpt && python -m metagpt",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["agents", "coding"],
            false,
            true,
            true,
        ),
        tool(
            "agentverse",
            "AgentUniverse",
            "https://github.com/alipay/agentUniverse",
            "Enterprise multi-agent platform with domain knowledge and collaboration.",
            "pip install agentUniverse && python -m agentuniverse",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["agents", "enterprise"],
            false,
            true,
            false,
        ),
        tool(
            "deer-flow",
            "DeerFlow",
            "https://github.com/bytedance/deer-flow",
            "Deep research agent with iterative refinement and source tracing.",
            "pip install -e . && python main.py",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["research", "deep-dive"],
            false,
            true,
            true,
        ),
        tool(
            "markitdown",
            "MarkItDown",
            "https://github.com/microsoft/markitdown",
            "Converts Office, PDF, HTML, and media files to clean Markdown.",
            "pip install markitdown && python -m markitdown",
            "pip",
            vec![],
            vec!["documents", "conversion"],
            false,
            false,
            false,
        ),
        tool(
            "playwright-mcp",
            "Playwright MCP",
            "https://github.com/microsoft/playwright-mcp",
            "Browser automation server via MCP protocol for AI-driven web control.",
            "bun run start",
            "bun",
            vec![],
            vec!["browser", "mcp", "automation"],
            false,
            false,
            false,
        ),
        tool(
            "meshgen",
            "MeshGen",
            "https://github.com/MeshGenAI/meshgen",
            "AI-driven 3D mesh generation from text prompts.",
            "pip install -e . && python main.py",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["3d", "generation"],
            false,
            true,
            false,
        ),
        tool(
            "open-interpreter",
            "Open Interpreter",
            "https://github.com/OpenInterpreter/open-interpreter",
            "Local code execution and chat interpreter supporting all languages.",
            "pip install open-interpreter && interpreter",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["coding", "interpreter"],
            false,
            true,
            true,
        ),
        tool(
            "continue-dev",
            "Continue.dev",
            "https://github.com/continuedev/continue",
            "Open-source AI code assistant IDE extension for Cursor and VS Code.",
            "bun run dev",
            "bun",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["coding", "ide"],
            false,
            true,
            false,
        ),
        tool(
            "pocketflow",
            "PocketFlow",
            "https://github.com/the-pocket/PocketFlow",
            "Minimalist 100-line LLM orchestration framework.",
            "pip install pocketflow && python main.py",
            "pip",
            vec!["OPENAI_API_KEY"],
            vec!["orchestration", "lightweight"],
            false,
            true,
            false,
        ),
        tool(
            "agno",
            "Agno",
            "https://github.com/agno-agi/agno",
            "High-performance agent framework with multimodal and memory support.",
            "pip install agno && python main.py",
            "pip",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["agents", "multimodal"],
            false,
            true,
            true,
        ),
        // ── Internal capabilities ─────────────────────────────────────────────
        tool(
            "open-in-code",
            "Open in Code",
            "internal://open-in-code",
            "Opens the active managed workspace in Cursor or VS Code with STATE.md ready.",
            "internal",
            "internal",
            Vec::new(),
            vec!["ide", "internal"],
            false,
            false,
            false,
        ),
        tool(
            "universal-ralph-loop",
            "Universal Ralph Loop",
            "internal://universal-ralph-loop",
            "Runs a model-selectable overnight Ralph loop across one or more managed tools.",
            "internal",
            "internal",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY", "GROK_API_KEY"],
            vec!["orchestration", "overnight", "internal"],
            false,
            true,
            true,
        ),
        tool(
            "memory-spine",
            "Memory Spine",
            "internal://memory-spine",
            "Persistent memory layer: writes run reports, notes, and results for all tools.",
            "internal",
            "internal",
            Vec::new(),
            vec!["memory", "internal"],
            false,
            false,
            false,
        ),
        tool(
            "kaizen-tasks",
            "Kaizen Tasks",
            "internal://kaizen-tasks",
            "Continuous improvement task tracker wired to every workflow and tool run.",
            "internal",
            "internal",
            Vec::new(),
            vec!["tasks", "kaizen", "internal"],
            false,
            false,
            false,
        ),
        tool(
            "ollama-local",
            "Ollama Local",
            "internal://ollama-local",
            "Local Ollama model manager: install, pull, and route requests to local LLMs.",
            "internal",
            "internal",
            vec!["OLLAMA_API_KEY"],
            vec!["local-models", "ollama", "internal"],
            false,
            true,
            false,
        ),
        tool(
            "browser-agent",
            "Browser Agent",
            "internal://browser-agent",
            "MCP-driven browser automation layer over Edge with click, type, scrape, navigate.",
            "internal",
            "internal",
            Vec::new(),
            vec!["browser", "mcp", "internal"],
            false,
            false,
            false,
        ),
    ]
});

pub fn all_tools() -> Vec<ToolManifest> {
    BUILTIN_TOOLS.clone()
}

#[allow(dead_code)]
pub fn tool_by_id(id: &str) -> Option<ToolManifest> {
    BUILTIN_TOOLS.iter().find(|t| t.id == id).cloned()
}

#[allow(clippy::too_many_arguments)]
fn tool(
    id: &str,
    name: &str,
    repo_url: &str,
    description: &str,
    launch_command: &str,
    install_method: &str,
    required_keys: Vec<&str>,
    categories: Vec<&str>,
    needs_sandbox: bool,
    supports_ollama: bool,
    supports_voice: bool,
) -> ToolManifest {
    ToolManifest {
        id: id.to_string(),
        name: name.to_string(),
        repo_url: repo_url.to_string(),
        description: description.to_string(),
        launch_command: launch_command.to_string(),
        install_method: install_method.to_string(),
        status: "pending".to_string(),
        open_in_code: true,
        needs_sandbox,
        required_keys: required_keys.into_iter().map(str::to_string).collect(),
        categories: categories.into_iter().map(str::to_string).collect(),
        supports_ollama,
        supports_voice,
    }
}
