use once_cell::sync::Lazy;

use crate::models::{ApiProvider, ToolManifest};

pub static BUILTIN_TOOLS: Lazy<Vec<ToolManifest>> = Lazy::new(|| {
    vec![
        // ── Research ────────────────────────────────────────────────────────
        tool(
            "perplexica",
            "Perplexica",
            "https://github.com/ItzCrazyKns/Perplexica",
            "AI-powered search engine with multi-model support. Research engine for deep overnight workflows.",
            "bun run dev",
            "research",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["research", "search", "ai"],
            true,
        ),
        tool(
            "autoresearch",
            "AutoResearch",
            "https://github.com/ur-whitelab/autoresearch",
            "Iterative multi-agent research runner with synthesis and citations.",
            "bun run dev",
            "research",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["research", "agents"],
            false,
        ),
        tool(
            "storm",
            "STORM",
            "https://github.com/stanford-oval/storm",
            "Stanford STORM: Research and long-form article generation from web sources.",
            "python storm_wiki/storm_wiki.py",
            "research",
            vec!["OPENAI_API_KEY"],
            vec!["research", "writing"],
            false,
        ),
        // ── Coding / Agent ─────────────────────────────────────────────────
        tool(
            "get-shit-done",
            "Get Shit Done",
            "https://github.com/gsd-build/get-shit-done",
            "Runs the AI execution loop as a managed Bun workspace.",
            "bun run dev",
            "coding",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["agents", "coding"],
            false,
        ),
        tool(
            "claudia",
            "Claudia",
            "https://github.com/getclaudia/claudia",
            "Consolidates memory and agent notes into a durable workspace.",
            "bun run dev",
            "coding",
            vec!["ANTHROPIC_API_KEY"],
            vec!["memory", "agents"],
            false,
        ),
        tool(
            "claude-code-templates",
            "Claude Code Templates",
            "https://github.com/davila7/claude-code-templates",
            "Bootstraps prompt and workflow templates for managed coding runs.",
            "bun run dev",
            "coding",
            vec!["ANTHROPIC_API_KEY"],
            vec!["templates", "coding"],
            false,
        ),
        tool(
            "open-hands",
            "OpenHands",
            "https://github.com/All-Hands-AI/OpenHands",
            "Open platform for AI software engineers. Full repo automation.",
            "python -m openhands.core.main",
            "coding",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["agents", "coding", "automation"],
            true,
        ),
        tool(
            "aider",
            "Aider",
            "https://github.com/paul-gauthier/aider",
            "AI pair programming in your terminal. Works with any model.",
            "aider",
            "coding",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY"],
            vec!["coding", "pair-programming"],
            false,
        ),
        tool(
            "continue",
            "Continue",
            "https://github.com/continuedev/continue",
            "Open-source autopilot for VS Code and JetBrains.",
            "bun run dev",
            "coding",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["coding", "ide"],
            false,
        ),
        tool(
            "goose",
            "Goose",
            "https://github.com/block/goose",
            "Block's open-source AI coding agent with tool use.",
            "bun run dev",
            "coding",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY"],
            vec!["agents", "coding"],
            false,
        ),
        // ── Task / Project ──────────────────────────────────────────────────
        tool(
            "vibe-kanban",
            "Vibe Kanban",
            "https://github.com/BloopAI/vibe-kanban",
            "Tracks work items and AI progress in a board-style workspace.",
            "bun run dev",
            "tasks",
            vec!["OPENAI_API_KEY"],
            vec!["kanban", "tasks"],
            false,
        ),
        tool(
            "linear-clone",
            "MiniLinear",
            "https://github.com/theteleporter/black-hole",
            "Lightweight issue tracker with AI triage.",
            "bun run dev",
            "tasks",
            vec!["OPENAI_API_KEY"],
            vec!["tasks", "issues"],
            false,
        ),
        // ── Multi-Model / Council ───────────────────────────────────────────
        tool(
            "llm-council",
            "LLM Council",
            "https://github.com/microsoft/llmlingua",
            "Model voting layer for combined workflows and overnight loops.",
            "bun run dev",
            "multi-model",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY"],
            vec!["multi-model", "voting"],
            false,
        ),
        tool(
            "langchain",
            "LangChain",
            "https://github.com/langchain-ai/langchainjs",
            "Build context-aware reasoning applications over any LLM.",
            "bun run dev",
            "multi-model",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["chains", "agents"],
            false,
        ),
        tool(
            "litellm",
            "LiteLLM",
            "https://github.com/BerriAI/litellm",
            "Universal API proxy for 100+ LLMs with fallback and cost tracking.",
            "litellm --port 4000",
            "multi-model",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY"],
            vec!["proxy", "multi-model"],
            false,
        ),
        // ── Browser / Web Automation ────────────────────────────────────────
        tool(
            "playwright-mcp",
            "Playwright MCP",
            "https://github.com/microsoft/playwright-mcp",
            "Browser automation MCP server — control any webpage with AI.",
            "bun run start",
            "browser",
            vec![],
            vec!["browser", "mcp", "automation"],
            false,
        ),
        tool(
            "capture-mcp",
            "Capture MCP Browser",
            "https://github.com/irthomasthomas/undecidability",
            "Screenshot and DOM capture MCP for browser-based research.",
            "bun run start",
            "browser",
            vec![],
            vec!["browser", "mcp", "capture"],
            false,
        ),
        tool(
            "stagehand",
            "Stagehand",
            "https://github.com/browserbase/stagehand",
            "AI-first browser automation framework from Browserbase.",
            "bun run dev",
            "browser",
            vec!["BROWSERBASE_API_KEY", "OPENAI_API_KEY"],
            vec!["browser", "automation"],
            false,
        ),
        tool(
            "firecrawl",
            "Firecrawl",
            "https://github.com/mendableai/firecrawl",
            "Turn any website into LLM-ready markdown. Scrape, crawl, extract.",
            "bun run dev",
            "browser",
            vec!["FIRECRAWL_API_KEY"],
            vec!["scraping", "crawling"],
            false,
        ),
        tool(
            "crawlee",
            "Crawlee",
            "https://github.com/apify/crawlee",
            "Web scraping and browser automation library (Apify).",
            "bun run dev",
            "browser",
            vec!["APIFY_TOKEN"],
            vec!["scraping", "automation"],
            false,
        ),
        // ── Memory / Knowledge ──────────────────────────────────────────────
        tool(
            "mem0",
            "Mem0",
            "https://github.com/mem0ai/mem0",
            "Memory layer for AI applications. Persistent user memory across sessions.",
            "python server.py",
            "memory",
            vec!["OPENAI_API_KEY", "MEM0_API_KEY"],
            vec!["memory", "personalization"],
            false,
        ),
        tool(
            "chroma",
            "ChromaDB",
            "https://github.com/chroma-core/chroma",
            "Open-source vector database for AI memory and search.",
            "chroma run",
            "memory",
            vec!["OPENAI_API_KEY"],
            vec!["memory", "vectors", "search"],
            false,
        ),
        tool(
            "obsidian-ai",
            "Obsidian AI Bridge",
            "https://github.com/logancyang/obsidian-copilot",
            "AI copilot for Obsidian — chat with your notes and memories.",
            "bun run dev",
            "memory",
            vec!["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
            vec!["notes", "memory", "knowledge"],
            false,
        ),
        // ── Voice / Audio ───────────────────────────────────────────────────
        tool(
            "whisper",
            "Whisper (Local)",
            "https://github.com/openai/whisper",
            "OpenAI Whisper — local speech-to-text for voice commands.",
            "python -m whisper.transcribe",
            "voice",
            vec![],
            vec!["voice", "transcription", "local"],
            false,
        ),
        tool(
            "whisper-web",
            "Whisper.cpp Web",
            "https://github.com/ggerganov/whisper.cpp",
            "C++ port of Whisper — runs in browser via WASM.",
            "bun run dev",
            "voice",
            vec![],
            vec!["voice", "wasm", "local"],
            false,
        ),
        tool(
            "eleven-labs-voice",
            "ElevenLabs Voice",
            "https://github.com/elevenlabs/elevenlabs-python",
            "High-quality AI text-to-speech with voice cloning.",
            "python tts.py",
            "voice",
            vec!["ELEVENLABS_API_KEY"],
            vec!["voice", "tts"],
            false,
        ),
        // ── MCP Servers ─────────────────────────────────────────────────────
        tool(
            "filesystem-mcp",
            "Filesystem MCP",
            "https://github.com/modelcontextprotocol/servers",
            "Official MCP filesystem server — read/write files safely.",
            "npx @modelcontextprotocol/server-filesystem",
            "mcp",
            vec![],
            vec!["mcp", "files"],
            false,
        ),
        tool(
            "github-mcp",
            "GitHub MCP",
            "https://github.com/modelcontextprotocol/servers",
            "Official MCP GitHub server — manage repos, PRs, issues with AI.",
            "npx @modelcontextprotocol/server-github",
            "mcp",
            vec!["GITHUB_TOKEN"],
            vec!["mcp", "github"],
            false,
        ),
        tool(
            "brave-search-mcp",
            "Brave Search MCP",
            "https://github.com/modelcontextprotocol/servers",
            "Official MCP Brave Search server — real-time web search for agents.",
            "npx @modelcontextprotocol/server-brave-search",
            "mcp",
            vec!["BRAVE_API_KEY"],
            vec!["mcp", "search"],
            false,
        ),
        tool(
            "sqlite-mcp",
            "SQLite MCP",
            "https://github.com/modelcontextprotocol/servers",
            "Official MCP SQLite server — structured data queries for agents.",
            "npx @modelcontextprotocol/server-sqlite",
            "mcp",
            vec![],
            vec!["mcp", "database"],
            false,
        ),
        tool(
            "sequential-thinking-mcp",
            "Sequential Thinking MCP",
            "https://github.com/modelcontextprotocol/servers",
            "Chain-of-thought reasoning server — structured problem decomposition.",
            "npx @modelcontextprotocol/server-sequential-thinking",
            "mcp",
            vec![],
            vec!["mcp", "reasoning"],
            false,
        ),
        // ── UI / Design ─────────────────────────────────────────────────────
        tool(
            "v0",
            "v0 (Vercel)",
            "https://github.com/vercel/v0-next",
            "Generate UI components from natural language descriptions.",
            "bun run dev",
            "design",
            vec!["VERCEL_TOKEN"],
            vec!["ui", "design", "generation"],
            false,
        ),
        // ── Data / Analytics ────────────────────────────────────────────────
        tool(
            "datasette",
            "Datasette",
            "https://github.com/simonw/datasette",
            "Explore and publish data as interactive SQLite databases.",
            "datasette serve",
            "data",
            vec![],
            vec!["data", "sql", "analytics"],
            false,
        ),
        tool(
            "evidence",
            "Evidence",
            "https://github.com/evidence-dev/evidence",
            "Build data apps and reports from SQL queries + Markdown.",
            "bun run dev",
            "data",
            vec!["OPENAI_API_KEY"],
            vec!["data", "reports", "analytics"],
            false,
        ),
        // ── Internal ────────────────────────────────────────────────────────
        tool(
            "open-in-code",
            "Open in Code",
            "internal://open-in-code",
            "Opens the active managed workspace in Cursor or VS Code with STATE.md ready.",
            "internal",
            "internal",
            vec![],
            vec!["internal"],
            false,
        ),
        tool(
            "universal-ai-loop",
            "Universal AI Loop",
            "internal://universal-ai-loop",
            "Runs a model-selectable overnight AI loop across one or more managed tools.",
            "internal",
            "internal",
            vec!["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY"],
            vec!["internal", "overnight"],
            false,
        ),
        tool(
            "voice-command",
            "Voice Command",
            "internal://voice-command",
            "Web Speech API voice commander — say commands to control AmitOS.",
            "internal",
            "internal",
            vec![],
            vec!["voice", "internal"],
            false,
        ),
        tool(
            "memory-spine",
            "Memory Spine",
            "internal://memory-spine",
            "AmitOS persistent memory — capture, search, and synthesize knowledge.",
            "internal",
            "internal",
            vec![],
            vec!["memory", "internal"],
            false,
        ),
    ]
});

pub static API_PROVIDERS: Lazy<Vec<ApiProvider>> = Lazy::new(|| {
    vec![
        // ── Language Models ─────────────────────────────────────────────────
        provider("anthropic", "Anthropic (Claude)", "llm", "ANTHROPIC_API_KEY", "https://console.anthropic.com", "Claude 3.5 Sonnet, Claude 3 Opus, Haiku", "#d97706"),
        provider("openai", "OpenAI", "llm", "OPENAI_API_KEY", "https://platform.openai.com/api-keys", "GPT-4o, GPT-4 Turbo, o1, o3-mini", "#10b981"),
        provider("google-ai", "Google AI (Gemini)", "llm", "GEMINI_API_KEY", "https://aistudio.google.com/app/apikey", "Gemini 1.5 Pro, Flash, Ultra", "#3b82f6"),
        provider("xai", "xAI (Grok)", "llm", "GROK_API_KEY", "https://console.x.ai", "Grok-2, Grok-1.5", "#6366f1"),
        provider("mistral", "Mistral AI", "llm", "MISTRAL_API_KEY", "https://console.mistral.ai/api-keys", "Mistral Large, Nemo, Codestral", "#8b5cf6"),
        provider("cohere", "Cohere", "llm", "COHERE_API_KEY", "https://dashboard.cohere.com/api-keys", "Command R+, Command R, Embed", "#ec4899"),
        provider("together", "Together AI", "llm", "TOGETHER_API_KEY", "https://api.together.xyz/settings/api-keys", "70B+ open models, Mixtral, LLaMA", "#f59e0b"),
        provider("groq", "Groq", "llm", "GROQ_API_KEY", "https://console.groq.com/keys", "Ultra-fast inference for LLaMA, Mixtral", "#ef4444"),
        provider("perplexity", "Perplexity", "llm", "PERPLEXITY_API_KEY", "https://www.perplexity.ai/settings/api", "Online LLM with real-time web search", "#14b8a6"),
        provider("deepseek", "DeepSeek", "llm", "DEEPSEEK_API_KEY", "https://platform.deepseek.com/api_keys", "DeepSeek-R1, DeepSeek-V3, Coder", "#6366f1"),
        provider("fireworks", "Fireworks AI", "llm", "FIREWORKS_API_KEY", "https://fireworks.ai/account/api-keys", "Fast open model inference", "#f97316"),
        provider("openrouter", "OpenRouter", "llm", "OPENROUTER_API_KEY", "https://openrouter.ai/keys", "Unified API for 100+ models", "#a855f7"),
        provider("replicate", "Replicate", "llm", "REPLICATE_API_TOKEN", "https://replicate.com/account/api-tokens", "Open source model hosting", "#06b6d4"),
        provider("huggingface", "HuggingFace", "llm", "HF_TOKEN", "https://huggingface.co/settings/tokens", "Transformers, Inference API, Spaces", "#fbbf24"),
        provider("vertex", "Google Vertex AI", "llm", "GOOGLE_APPLICATION_CREDENTIALS", "https://console.cloud.google.com", "Gemini, PaLM 2, Codey on GCP", "#3b82f6"),
        provider("bedrock", "AWS Bedrock", "llm", "AWS_ACCESS_KEY_ID", "https://aws.amazon.com/bedrock", "Claude, Titan, Llama on AWS", "#f59e0b"),
        provider("azure-openai", "Azure OpenAI", "llm", "AZURE_OPENAI_API_KEY", "https://portal.azure.com", "OpenAI models on Azure", "#0ea5e9"),
        provider("ai21", "AI21 Labs", "llm", "AI21_API_KEY", "https://studio.ai21.com/account/api-key", "Jurassic-2, Jamba models", "#8b5cf6"),
        provider("cerebras", "Cerebras", "llm", "CEREBRAS_API_KEY", "https://cloud.cerebras.ai", "Ultra-fast wafer-scale AI inference", "#ef4444"),
        provider("nvidia-nim", "NVIDIA NIM", "llm", "NVIDIA_API_KEY", "https://build.nvidia.com", "NVIDIA hosted open models", "#10b981"),
        // ── Image Generation ─────────────────────────────────────────────────
        provider("stability", "Stability AI", "image", "STABILITY_API_KEY", "https://platform.stability.ai/account/keys", "Stable Diffusion 3, SDXL", "#8b5cf6"),
        provider("midjourney", "Midjourney", "image", "MIDJOURNEY_API_KEY", "https://www.midjourney.com", "High-quality artistic image generation", "#a855f7"),
        provider("fal-ai", "fal.ai", "image", "FAL_KEY", "https://fal.ai/dashboard/keys", "Fast Flux, SD, video generation", "#ec4899"),
        provider("ideogram", "Ideogram", "image", "IDEOGRAM_API_KEY", "https://ideogram.ai/api", "Text-in-image generation specialist", "#f59e0b"),
        provider("leonardo", "Leonardo.ai", "image", "LEONARDO_API_KEY", "https://app.leonardo.ai/settings", "Game assets, concept art generation", "#6366f1"),
        // ── Search ────────────────────────────────────────────────────────────
        provider("brave", "Brave Search", "search", "BRAVE_API_KEY", "https://api.search.brave.com/register", "Privacy-first web search API", "#f97316"),
        provider("serper", "Serper (Google Search)", "search", "SERPER_API_KEY", "https://serper.dev/api-key", "Google Search results API", "#10b981"),
        provider("tavily", "Tavily", "search", "TAVILY_API_KEY", "https://tavily.com", "AI-optimized search API for agents", "#3b82f6"),
        provider("exa", "Exa.ai", "search", "EXA_API_KEY", "https://exa.ai/api", "Neural search for semantic queries", "#8b5cf6"),
        // ── Web Scraping / Data ───────────────────────────────────────────────
        provider("firecrawl", "Firecrawl", "data", "FIRECRAWL_API_KEY", "https://firecrawl.dev", "Website-to-LLM scraping and crawling", "#ef4444"),
        provider("apify", "Apify", "data", "APIFY_TOKEN", "https://console.apify.com/account/integrations", "Web scraping and automation platform", "#14b8a6"),
        provider("phantombuster", "PhantomBuster", "data", "PHANTOMBUSTER_API_KEY", "https://phantombuster.com/phantombuster", "Social media data extraction", "#a855f7"),
        // ── Communication ─────────────────────────────────────────────────────
        provider("slack", "Slack", "communication", "SLACK_BOT_TOKEN", "https://api.slack.com/apps", "Team messaging and workflow automation", "#fbbf24"),
        provider("discord", "Discord", "communication", "DISCORD_TOKEN", "https://discord.com/developers/applications", "Community and notification bots", "#6366f1"),
        provider("telegram", "Telegram", "communication", "TELEGRAM_BOT_TOKEN", "https://t.me/BotFather", "Messaging bot for notifications", "#0ea5e9"),
        provider("sendgrid", "SendGrid (Email)", "communication", "SENDGRID_API_KEY", "https://app.sendgrid.com/settings/api_keys", "Transactional email delivery", "#10b981"),
        // ── Voice / Audio ─────────────────────────────────────────────────────
        provider("elevenlabs", "ElevenLabs", "voice", "ELEVENLABS_API_KEY", "https://elevenlabs.io/app/profile", "Natural AI text-to-speech", "#f59e0b"),
        provider("openai-tts", "OpenAI TTS/STT", "voice", "OPENAI_API_KEY", "https://platform.openai.com/api-keys", "Whisper STT + TTS-1 built-in", "#10b981"),
        provider("deepgram", "Deepgram", "voice", "DEEPGRAM_API_KEY", "https://console.deepgram.com", "Real-time speech transcription", "#8b5cf6"),
        provider("assemblyai", "AssemblyAI", "voice", "ASSEMBLYAI_API_KEY", "https://www.assemblyai.com/dashboard", "Speech understanding + diarization", "#ec4899"),
        // ── Cloud / Infrastructure ────────────────────────────────────────────
        provider("github", "GitHub", "cloud", "GITHUB_TOKEN", "https://github.com/settings/tokens", "Repos, Issues, Actions API", "#6366f1"),
        provider("vercel", "Vercel", "cloud", "VERCEL_TOKEN", "https://vercel.com/account/tokens", "Deploy and manage web projects", "#0ea5e9"),
        provider("supabase", "Supabase", "cloud", "SUPABASE_SERVICE_ROLE_KEY", "https://supabase.com/dashboard/account/tokens", "Postgres, Auth, Storage, Realtime", "#10b981"),
        provider("planetscale", "PlanetScale", "cloud", "PLANETSCALE_TOKEN", "https://app.planetscale.com/settings/api-tokens", "Serverless MySQL platform", "#f59e0b"),
        provider("cloudflare", "Cloudflare AI", "cloud", "CLOUDFLARE_API_TOKEN", "https://dash.cloudflare.com/profile/api-tokens", "Workers AI, R2, D1, KV", "#f97316"),
        provider("browserbase", "Browserbase", "cloud", "BROWSERBASE_API_KEY", "https://browserbase.com/overview", "Hosted browser automation for AI agents", "#8b5cf6"),
        // ── Payments / Business ───────────────────────────────────────────────
        provider("stripe", "Stripe", "business", "STRIPE_SECRET_KEY", "https://dashboard.stripe.com/apikeys", "Payments, subscriptions, billing", "#6366f1"),
        provider("notion", "Notion", "business", "NOTION_TOKEN", "https://www.notion.so/my-integrations", "Notion workspace API", "#0ea5e9"),
        provider("airtable", "Airtable", "business", "AIRTABLE_API_KEY", "https://airtable.com/create/tokens", "Database-spreadsheet hybrid", "#ef4444"),
        provider("linear", "Linear", "business", "LINEAR_API_KEY", "https://linear.app/settings/api", "Issue tracking for software teams", "#5e6ad2"),
        provider("perplexica-keys", "Perplexica Local", "misc", "PERPLEXICA_KEYS", "https://github.com/ItzCrazyKns/Perplexica", "Perplexica local config keys", "#14b8a6"),
    ]
});

pub fn all_tools() -> Vec<ToolManifest> {
    BUILTIN_TOOLS.clone()
}

pub fn all_providers() -> Vec<ApiProvider> {
    API_PROVIDERS.clone()
}

#[allow(clippy::too_many_arguments)]
fn tool(
    id: &str,
    name: &str,
    repo_url: &str,
    description: &str,
    launch_command: &str,
    category: &str,
    required_keys: Vec<&str>,
    tags: Vec<&str>,
    needs_sandbox: bool,
) -> ToolManifest {
    ToolManifest {
        id: id.to_string(),
        name: name.to_string(),
        repo_url: repo_url.to_string(),
        description: description.to_string(),
        launch_command: launch_command.to_string(),
        status: "ready".to_string(),
        category: category.to_string(),
        open_in_code: true,
        needs_sandbox,
        required_keys: required_keys.into_iter().map(str::to_string).collect(),
        tags: tags.into_iter().map(str::to_string).collect(),
    }
}

#[allow(clippy::too_many_arguments)]
fn provider(
    id: &str,
    name: &str,
    category: &str,
    key_name: &str,
    url: &str,
    description: &str,
    color: &str,
) -> ApiProvider {
    ApiProvider {
        id: id.to_string(),
        name: name.to_string(),
        category: category.to_string(),
        key_name: key_name.to_string(),
        url: url.to_string(),
        description: description.to_string(),
        color: color.to_string(),
    }
}
